# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: backend_layerframe_development
test:
  <<: *default
  database: backend_layerframe_test
production:
  <<: *default
  database: backend_layerframe_production
  username: backend_layerframe
  password: <%= ENV['REALLY-GOOD-PHOTOS_DATABASE_PASSWORD'] %>
